SET NOCOUNT ON

DECLARE @CHAVENOTA	VARCHAR(50)
DECLARE @USUARIO	VARCHAR(20)

SET @CHAVENOTA = #CHAVENOTA /*'51190109490719000122550010000005061575478438'*/
SET @USUARIO = #USUARIO

DELETE FROM GWGERACTE WHERE USUARIO = @USUARIO
DELETE FROM GWGERAREBO WHERE USUARIO = @USUARIO

INSERT INTO GWGERACTE
SELECT @USUARIO, RTRIM(CMOVNF.CHAVE_NFE) AS CHAVE_NFE,
	RTRIM(CMOVNF.NOTA) AS [NF], 
	RTRIM(SPDEST.PES_CODIGO) AS [COD.DEST],
	RTRIM(CMOVNF.NOME_CLIENTE) AS [NOME.DEST], 
	RTRIM(CMOVNF.CNPJ) AS [CNPJ.D],
	RTRIM(CMOVNF.CIDADE_COD) AS [CM.DEST],
	RTRIM(CMOVNF.CIDADE) AS [CID.DEST.],
	RTRIM(CMOVNF.ESTADO) AS [UF.DEST.],
	RTRIM(CMOVNF.PLACA) AS [PLACA], 
	RTRIM(CMOVNF.MOTORISTA_CPF) AS [CPF.MOTORISTA],
	RTRIM(CITENF.CODIGO) AS [C.PROD],
	RTRIM(CITENF.DESCRICAO) AS [PRODUTO],
	RTRIM(CITENF.SIT_TRIBUTARIA) AS [ST],
	RTRIM(SPEND2.COD_CIDADE) AS [CM.ORI],
	RTRIM(SCIDADES.DESCRICAO) AS [CID.ORI.],
	RTRIM(SCIDADES.COD_ESTADOS) AS [UF.ORI],
	RTRIM(SP2.PES_CODIGO) AS [COD.ORI],
	RTRIM(SP2.CNPJ_CPF) AS [CNPJ.R/O],
	RTRIM(SP2.RAZAO_SOCIAL) AS [REMET/ORIGEM],
	RTRIM(CAST((CITENF.QTDE) AS NUMERIC(14,2))) AS [PESONF],
	RTRIM(CITENF.CFOP) AS [CFOP],
	RTRIM(SPM.PES_CODIGO) AS [COD.MOTO],
	RTRIM(CMOVNF.MOTORISTA) AS [MOTORISTA],
	CASE WHEN PSGA.DBO.CMOVNF.DADOS_ADICIO LIKE '%ARAPU%'  THEN 'FAZENDA ARAPUA' WHEN PSGA.DBO.CMOVNF.DADOS_ADICIO LIKE '%PEABIRU%' THEN 'FAZENDA PEABIRU'
	WHEN PSGA.DBO.CMOVNF.DADOS_ADICIO LIKE '%PALMITAL%' THEN 'FAZENDA PALMITAL' WHEN PSGA.DBO.CMOVNF.DADOS_ADICIO LIKE '%DOURADO%' THEN 'FAZENDA SONHO DOURADO'
	WHEN PSGA.DBO.CMOVNF.DADOS_ADICIO LIKE '%APARECIDA%' THEN 'FAZENDA N. S. APARECIDA' WHEN PSGA.DBO.CMOVNF.DADOS_ADICIO LIKE '%SENHORA%' THEN 'FAZENDA N. S. APARECIDA'
	WHEN PSGA.DBO.CMOVNF.DADOS_ADICIO LIKE '%UMUARAMA I%' THEN 'FAZENDA UMUARAMA I' WHEN PSGA.DBO.CMOVNF.DADOS_ADICIO LIKE '%UMUARAMA II%' THEN 'FAZENDA UMUARAMA II'
	WHEN PSGA.DBO.CMOVNF.DADOS_ADICIO LIKE '%CRISTAL%' THEN 'FAZENDA CRISTAL' WHEN PSGA.DBO.CMOVNF.DADOS_ADICIO LIKE '%CACIQUE%' THEN 'FAZENDA CACIQUE'
	WHEN PSGA.DBO.CMOVNF.DADOS_ADICIO LIKE '%BOA%' THEN 'FAZENDA BOA ESPERANCA' WHEN PSGA.DBO.CMOVNF.DADOS_ADICIO LIKE '%ARAPONGAS%' THEN 'FAZENDA ARAPONGAS'
	WHEN PSGA.DBO.CMOVNF.DADOS_ADICIO LIKE '%HUMAITA%' THEN 'FAZENDA HUMAITA' WHEN PSGA.DBO.CMOVNF.DADOS_ADICIO LIKE '%MARFAL%' THEN 'FAZENDA MARFAL' ELSE 'VERIFICAR'
	END AS [FAZENDA], 
	RTRIM(SPTRANSP.RNTRC) AS [RNTRC],
	RTRIM(VEIC.COD_VEICULO) AS [COD.VEIC],
	RTRIM(SPTRANSP.PES_CODIGO) AS [COD.TRANSP],
	RTRIM(SPTRANSP.RAZAO_SOCIAL) AS [TRANSP],
	RTRIM(SPTRANSP.CNPJ_CPF) AS [CPF-CNPJ.TRANSP],
	RTRIM(CAST((CMOVNF.PESO_BRUTO) AS NUMERIC(14,2))) AS [PESO.BRUTO],
	RTRIM(CAST((CITENF.VALOR_TOTAL) AS MONEY)) AS [VALOR_NF],
	DATEPART(DAY,(CMOVNF.DT_EMISSAO)) AS [DIA.EMISS],
	DATEPART(MONTH,(CMOVNF.DT_EMISSAO)) AS [MES.EMISS],
	DATEPART(YEAR,(CMOVNF.DT_EMISSAO)) AS [ANO.EMISS],
	CMOVNF.DT_EMISSAO AS [DATA.SIST],
	RTRIM(ISNULL(IFRNFTERCTE.ICONFRET_COD,'')) AS [CTE],
	RTRIM(ISNULL(IFRNFTERCTE.SERIE_COD,'')) AS [SERIE],
	CAST(CITENF.VLR_UN_SEM_DESC AS NUMERIC(14,2)) AS [VLR.UNIT],
	CAST(ISNULL(CTE.VLR_TOTAL_CTRC,0) AS NUMERIC(14,2)) AS VLR_TOTAL_CTRC,
	SPESSEND.PSE_TPEND AS [TPEND.DEST],
	SPEND2.PSE_TPEND AS [TPEND.REM],
	TRANSPEND.PSE_TPEND AS [TRANSP.ENDCOD],
	SPDEST.RAZAO_SOCIAL AS [DEST_RAZAO_SOCIAL],
	SPDEST.CNPJ_CPF AS [DEST_CPF_CNPJ],
	SPDEST.INST_EST_RG AS [DEST_INSC_EST_RG],
	SPDESTEND.ENDERECO AS [DEST_END],
	SPDESTEND.NUMERO AS [DEST_NUMERO],
	SPDESTEND.COMPLEMENTO AS [DEST_CPL],
	SPDESTEND.BAIRRO AS [DEST_BAIRRO],
	SPDESTEND.CEP AS [DEST_CEP],
	ISNULL(MDFE_ANT.COD_MANIFESTO,'') AS MDFE_ANT_NR,
	ISNULL(MDFE_ANT.SERIE,'') AS MDFE_ANT_SERIE,
	ISNULL(MDFE_ANT.DATA_DTTIME,CAST('1900-01-01' AS DATETIME)) MDFE_ANT_DATA,
	ISNULL(MDFE_ANT.GERADO,'') MDFE_ANT_GERADO,
	ISNULL(MDFE_ANT.ENCERRADO,'') MDFE_ANT_ENCERRADO,
	ISNULL(MDFE_ANT.CANCELADO,'') MDFE_ANT_CANCELADO,
	ISNULL(MDFE_ANT.MOTORISTA,'') MDFE_ANT_MOT_COD,
	ISNULL(MDFE_ANT.NOME,'') MDFE_ANT_MOT_NOME,
	ISNULL(MDFE_ANT.PLACA,'') MDFE_ANT_PLACA,
	ISNULL(MDFE.CODIGO,'') MDFE_COD,
	ISNULL(MDFE.SERIE,'') MDFE_SERIE,
	ISNULL(MDFE.DATA_EMISSAO,CAST('1900-01-01' AS DATETIME)) MDFE_DT_EMISSAO
FROM PSGA.DBO.CMOVNF (NOLOCK)

	INNER JOIN PSGA.DBO.CITENF (NOLOCK)		ON CMOVNF.NOTA = CITENF.NOTA AND CMOVNF.SERIE_COD = CITENF.SERIE_COD 
	INNER JOIN PSGA.DBO.CSERIES (NOLOCK)	ON CMOVNF.SERIE_COD = CSERIES.SERIE
	INNER JOIN PSGA.DBO.SCCUSTO (NOLOCK)	ON CSERIES.CENTRO_CUSTO = SCCUSTO.CODIGO
	INNER JOIN PSGA.DBO.SPESSEND (NOLOCK)	ON CMOVNF.CCLIENTE = SPESSEND.PES_CODIGO
											AND CMOVNF.TPENDERECO = SPESSEND.PSE_TPEND
	INNER JOIN PSGA.DBO.SPESSEND SPEND2 (NOLOCK) ON CSERIES.COD_PROD = SPEND2.PES_CODIGO 
	INNER JOIN PSGA.DBO.SCIDADES SCIDADES (NOLOCK) ON SCIDADES.CODIGO = SPEND2.COD_CIDADE
	CROSS APPLY (SELECT * FROM PSGACTE.DBO.SPESSOAS S (NOLOCK) WHERE CMOVNF.CNPJ = S.CNPJ_CPF) SPDEST 
	INNER JOIN PSGA.DBO.SPESSOAS (NOLOCK)	ON CMOVNF.CCLIENTE = SPESSOAS.PES_CODIGO AND SPESSOAS.CNPJ_CPF = SPDEST.CNPJ_CPF
	CROSS APPLY (SELECT TOP 1 * FROM PSGACTE.DBO.SPESSEND S (NOLOCK) WHERE SPDEST.PES_CODIGO = S.PES_CODIGO ORDER BY S.PSE_TPEND) SPDESTEND
	CROSS APPLY (SELECT TOP 1 * FROM PSGACTE.DBO.SPESSOAS S (NOLOCK) WHERE S.CNPJ_CPF = CMOVNF.MOTORISTA_CPF) SPM /*AQUI ESTA TRAZENDO MAIS RESULTADOS SEM O TOP*/
	CROSS APPLY (SELECT * FROM PSGACTE.DBO.SPESSOAS S (NOLOCK) WHERE S.INST_EST_RG = SCCUSTO.INSC_ESTADUAL 
																AND S.UF_CRC = SCCUSTO.UF_CAIXA_POSTAL) SP2
	CROSS APPLY (SELECT * FROM PSGACTE.DBO.SVEICULOS S (NOLOCK) WHERE CMOVNF.PLACA = S.PLACA) VEIC
	CROSS APPLY (SELECT * FROM PSGACTE.DBO.SPESSOAS S (NOLOCK) WHERE  VEIC.PES_COD_PROP = S.PES_CODIGO) SPTRANSP
	CROSS APPLY (SELECT * FROM PSGACTE.DBO.SPESSEND S (NOLOCK) WHERE SPTRANSP.PES_CODIGO = S.PES_CODIGO) TRANSPEND
	OUTER APPLY (SELECT * FROM PSGACTE.DBO.IFRNFTER S (NOLOCK) WHERE S.SERIE_COD = 'CTERMT' AND S.CHAVE_NF = CMOVNF.CHAVE_NFE) IFRNFTERCTE 
	OUTER APPLY (SELECT * FROM PSGACTE.DBO.ICMOVCTE S (NOLOCK) WHERE S.COD_STATUS = '100' AND IFRNFTERCTE.ICONFRET_COD = S.ICONFRET_COD) ICMOVCTERM
	/*CTE*/
	OUTER APPLY (SELECT VLR_TOTAL_CTRC FROM PSGACTE.DBO.ICONFRET I (NOLOCK) WHERE I.SERIE_COD = IFRNFTERCTE.SERIE_COD 
																	AND I.SPESSTRANSP_COD = IFRNFTERCTE.SPESSTRANSP_COD
																	AND I.ICONFRET_COD = IFRNFTERCTE.ICONFRET_COD) CTE
	/*MDFE ANT*/
	OUTER APPLY (SELECT TOP (1) IMANIDF.SERIE AS SERIE, IMANIDF.COD_MANIFESTO AS COD_MANIFESTO,
					CONVERT(VARCHAR,IMANIDF.DATA_EMISSAO,103) AS DATA,
					IMANIDF.DATA_EMISSAO AS DATA_DTTIME,
					CASE 
					 WHEN IMANIDF.MDF_GERADO  = '1'
					 THEN 'GERADO'
					 WHEN IMANIDF.MDF_GERADO = ''
						THEN 'NAO GERADO'
					END AS GERADO,
					CASE 
					 WHEN IMANIDF.MDF_ENCERRADO  = '1'
					 THEN 'ENCERRADO'
					 WHEN IMANIDF.MDF_ENCERRADO = ''
						THEN 'NAO ENCERRADO'
					END AS ENCERRADO,
					CASE 
					 WHEN IMANIDF.MDF_CANCELADO  = '1'
					 THEN 'CANCELADO'
					 WHEN IMANIDF.MDF_CANCELADO = ''
						THEN 'NAO CANCELADO'
					 END AS CANCELADO,
					IMANIDF.MOTORISTA AS MOTORISTA,
					SPESSOAS.RAZAO_SOCIAL AS NOME,
					SVEICULOS.PLACA AS PLACA
			FROM PSGACTE.DBO.IMANIDF (NOLOCK)
				INNER JOIN PSGACTE.DBO.SVEICULOS (NOLOCK)	ON SVEICULOS.COD_VEICULO = IMANIDF.VEICULO
				INNER JOIN PSGACTE.DBO.SPESSOAS (NOLOCK)	ON SPESSOAS.PES_CODIGO = IMANIDF.MOTORISTA
			WHERE
			SVEICULOS.PLACA = RTRIM(CMOVNF.PLACA) AND IMANIDF.MDF_GERADO = '1'
			ORDER BY COD_MANIFESTO DESC
			) MDFE_ANT
	/*MDFE*/
	OUTER APPLY (SELECT TOP 1 IMANIDF.COD_MANIFESTO AS CODIGO, IMANIDF.SERIE, IMANIDF.DATA_EMISSAO FROM PSGACTE.DBO.IMANIDF (NOLOCK)
					INNER JOIN PSGACTE.DBO.IMANINFE (NOLOCK) ON IMANIDF.COD_MANIFESTO = IMANINFE.COD_MANIFESTO 
															AND IMANINFE.SERIE_MANIFESTO = IMANIDF.SERIE
					INNER JOIN PSGACTE.DBO.IMANICTE (NOLOCK) ON IMANICTE.COD_MANIFESTO = IMANIDF.COD_MANIFESTO 
															AND IMANICTE.SERIE_MANIFESTO = IMANIDF.SERIE
				WHERE IMANINFE.CHAVE_NF = @CHAVENOTA) MDFE

WHERE CMOVNF.SPESSTRANSP_COD = '04749' AND CMOVNF.CHAVE_NFE = @CHAVENOTA AND CMOVNF.[STATUS] = '3' AND CMOVNF.NFE_GERADA = '1' AND CMOVNF.CANCELADA <> '1'

SET NOCOUNT OFF