DECLARE @CHAVENOTA	VARCHAR(50)
DECLARE @COD_MDFE	VARCHAR(10)
DECLARE @COD_NFE	VARCHAR(10)
DECLARE @COD_CTE	VARCHAR(10)
DECLARE @NR_MDFE	INT
DECLARE @NEXT_SEQ_COD_MDFE	INT
DECLARE @NEXT_SEQ_COD_CTE	INT
DECLARE @NEXT_SEQ_COD_NFE	INT
DECLARE @TRAN_NAME	VARCHAR(10)

SET @CHAVENOTA	= #CHAVENOTA

SET @TRAN_NAME = (SELECT ABS(CHECKSUM(NEWID())))
BEGIN TRAN @TRAN_NAME

SET @NEXT_SEQ_COD_MDFE = (SELECT (SHLANG.SEQ_NUM+1) FROM PSGACTE.DBO.SHLANG WHERE SHLANG.TP_OBJ = 'IMANIDF' AND SHLANG.OBJ = 'IMANIDF.COD_MANIFESTO')
SET @NEXT_SEQ_COD_CTE = (SELECT (SHLANG.SEQ_NUM+1) FROM PSGACTE.DBO.SHLANG WHERE SHLANG.TP_OBJ = 'IMANICTE' AND SHLANG.OBJ = 'IMANICTE.COD_IMANICTE')
SET @NEXT_SEQ_COD_NFE = (SELECT (SHLANG.SEQ_NUM+1) FROM PSGACTE.DBO.SHLANG WHERE SHLANG.TP_OBJ = 'IMANINFE' AND SHLANG.OBJ = 'IMANINFE.COD_IMANINFE')
SET @COD_MDFE	= REPLICATE('0', 8 - LEN(@NEXT_SEQ_COD_MDFE)) + RTrim(@NEXT_SEQ_COD_MDFE)
SET @COD_NFE	= REPLICATE('0', 8 - LEN(@NEXT_SEQ_COD_NFE)) + RTrim(@NEXT_SEQ_COD_NFE)
SET @COD_CTE	= REPLICATE('0', 8 - LEN(@NEXT_SEQ_COD_CTE)) + RTrim(@NEXT_SEQ_COD_CTE)
SET @NR_MDFE	= (SELECT (CSERIES.ULT_NUM+1) FROM PSGACTE.DBO.CSERIES WHERE CSERIES.SERIE = 'MDFE')

UPDATE PSGACTE.DBO.SHLANG
	SET SHLANG.SEQ_NUM = @NEXT_SEQ_COD_MDFE
FROM PSGACTE.DBO.SHLANG
	WHERE SHLANG.TP_OBJ = 'IMANIDF'
	AND SHLANG.OBJ = 'IMANIDF.COD_MANIFESTO'

UPDATE PSGACTE.DBO.CSERIES
	SET CSERIES.ULT_NUM = @NR_MDFE
WHERE CSERIES.SERIE = 'MDFE'

UPDATE PSGACTE.DBO.SHLANG
SET SHLANG.SEQ_NUM = @NEXT_SEQ_COD_NFE
FROM PSGACTE.DBO.SHLANG
WHERE SHLANG.TP_OBJ = 'IMANINFE'
AND SHLANG.OBJ = 'IMANINFE.COD_IMANINFE'


UPDATE PSGACTE.DBO.SHLANG
SET SHLANG.SEQ_NUM = @NEXT_SEQ_COD_CTE
FROM PSGACTE.DBO.SHLANG
WHERE SHLANG.TP_OBJ = 'IMANICTE'
AND SHLANG.OBJ = 'IMANICTE.COD_IMANICTE'

COMMIT TRAN @TRAN_NAME

INSERT INTO PSGACTE.DBO.IMANIDF (COD_MANIFESTO,SERIE,NR_MANIFESTO,DATA_EMISSAO,HORA_EMISSAO,COD_CCUSTO,TP_EMIT,TRANSPORTADOR,VEICULO,
[STATUS],MODAL,UFINI,UFFIM,COD_MUNI_CARREGA,MOTORISTA,COD_MUNI_DESCARREGA,VALOR_CARGA,COD_TPUNID,PESO_BRUTO,MDF_GERADO,TARA,REBOQUE1,
REBOQUE2,REBOQUE3,TARA_REBOQUE1,TARA_REBOQUE2,TARA_REBOQUE3,PRODUTO_PREDOMINANTE)

SELECT 
	@COD_MDFE AS [COD_MANIFESTO],
	'MDFE' AS [SERIE],
	@NR_MDFE AS [NR_MANIFESTO],
	GETDATE() AS [DATA_EMISSAO],
	'0000' AS [HORA_EMISSAO],
	CTE.CCU AS [COD_CCUSTO],
	'1' AS [TP_EMIT],
	CTE.COD_TRANSP AS [TRANSPORTADOR],
	CTE.CAVALO AS [VEICULO],
	'1' AS [STATUS],
	'1' AS [MODAL],
	CTE.UF_ORI AS [UFINI],
	CTE.UF_DEST AS [UFFIM],
	CTE.MUN_ORI AS [COD_MUNI_CARREGA],
	CTE.COD_MOT AS [MOTORISTA],
	CTE.MUN_DEST AS [COD_MUNI_DESCARREGA],
	CTE.VLR_PROD AS [VALOR_CARGA],
	'TN' AS [COD_TPUNID],
	CTE.PESO_TOT AS [PESO_BRUTO],
	'' AS [MDF_GERADO],
	CTE.C_TARA AS [TARA],
	CTE.REBOQ1 AS [REBOQUE1],
	CTE.REBOQ2 AS [REBOQUE2],
	CTE.REBOQ3 AS [REBOQUE3],
	CTE.R1_TARA AS [TARA_REBOQUE1],
	CTE.R2_TARA AS [TARA_REBOQUE2],
	CTE.R3_TARA AS [TARA_REBOQUE3],
	CTE.COD_PROD AS [PRODUTO_PREDOMINANTE]
FROM(
	SELECT 
		ICONFRET.ICONFRET_COD AS [CTE],
		ICONFRET.SERIE_COD AS [SERIE],
		ICONFRET.COD_CCUSTO AS [CCU],
		ICONFRET.SPESSTRANSP_COD AS [COD_TRANSP],
		ICONFRET.SPESMOT_COD AS [COD_MOT],
		ICONFRET.CPRODUTOS AS [COD_PROD],
		ICONFRET.VLR_TOTAL AS [VLR_PROD],
		CAST(ICONFRET.PESO*1000 AS NUMERIC(14,2)) AS [PESO_TOT],
		ICONFRET.VEICULO AS [CAVALO],
		SVEICULOS.TARA AS [C_TARA],
		ICONFRET.VEICULODOIS AS [REBOQ1],
		ISNULL(SREBOQ1.TARA,'0') AS [R1_TARA],
		ICONFRET.VEICULOTRES AS [REBOQ2],
		ISNULL(SREBOQ2.TARA,'0') AS [R2_TARA],
		ICONFRET.VEICULOQUATRO AS [REBOQ3],
		ISNULL(SREBOQ3.TARA,'0') AS [R3_TARA],
		ICONFRET.MUNI_ORIGEM AS [MUN_ORI],
		ICONFRET.UF_ORIGEM AS [UF_ORI],
		ICONFRET.MUNI_DESTINO AS [MUN_DEST],
		ICONFRET.UF_DESTINO AS [UF_DEST]
	FROM PSGACTE.DBO.ICONFRET (NOLOCK)
		INNER JOIN PSGACTE.DBO.IFRNFTER ON ICONFRET.ICONFRET_COD = IFRNFTER.ICONFRET_COD
		INNER JOIN PSGACTE.DBO.SVEICULOS ON SVEICULOS.COD_VEICULO = ICONFRET.VEICULO
		LEFT JOIN (SELECT * FROM PSGACTE.DBO.SVEICULOS)SREBOQ1 ON SREBOQ1.COD_VEICULO = ICONFRET.VEICULODOIS
		LEFT JOIN (SELECT * FROM PSGACTE.DBO.SVEICULOS)SREBOQ2 ON SREBOQ2.COD_VEICULO = ICONFRET.VEICULOTRES
		LEFT JOIN (SELECT * FROM PSGACTE.DBO.SVEICULOS)SREBOQ3 ON SREBOQ3.COD_VEICULO = ICONFRET.VEICULOQUATRO
	WHERE IFRNFTER.CHAVE_NF = @CHAVENOTA)CTE

INSERT INTO PSGACTE.DBO.IMANINFE (COD_IMANINFE,COD_MANIFESTO,SERIE_MANIFESTO,TP_MOV,CHAVE_NF)
VALUES(@COD_NFE,@COD_MDFE,'MDFE','2',@CHAVENOTA)

INSERT INTO PSGACTE.DBO.IMANCONT (COD_MANIFESTO,SERIE_MANIFESTO,COD_PESSOA,DESC_PESSOA)
VALUES(@COD_MDFE,'MDFE','04726','ROSIMERY T. MIRANDA TRANSPORTE')

INSERT INTO PSGACTE.DBO.IMANICTE (COD_IMANICTE,ICONFRET_COD,SERIE_COD,TRANSPORTADOR,COD_MANIFESTO,SERIE_MANIFESTO,MUNI_DESCARREGA)
SELECT
	@COD_CTE AS [COD_IMANICTE],
	IFRNFTER.ICONFRET_COD AS [ICONFRET_COD],
	IFRNFTER.SERIE_COD AS [SERIE_COD],
	IFRNFTER.SPESSTRANSP_COD AS [TRANSPORTADOR],
	IMANIDF.COD_MANIFESTO AS [COD_MANIFESTO],
	IMANIDF.SERIE AS [SERIE_MANIFESTO],
	IMANIDF.COD_MUNI_DESCARREGA AS [MUNI_DESCARREGA]
FROM PSGACTE.DBO.IMANIDF (NOLOCK)
INNER JOIN PSGACTE.DBO.IMANINFE (NOLOCK) ON IMANINFE.COD_MANIFESTO = IMANIDF.COD_MANIFESTO
INNER JOIN PSGACTE.DBO.IFRNFTER (NOLOCK) ON IMANINFE.CHAVE_NF = IFRNFTER.CHAVE_NF
WHERE IMANINFE.CHAVE_NF = @CHAVENOTA

/*
UPDATE SAGRM.DBO.GWGERACTE

SET GWGERACTE.MDFE_COD = (SELECT IMANIDF.COD_MANIFESTO FROM PSGACTE.DBO.IMANIDF 
							INNER JOIN PSGACTE.DBO.IMANINFE ON IMANIDF.COD_MANIFESTO = IMANINFE.COD_MANIFESTO
							WHERE IMANINFE.CHAVE_NF = @CHAVENOTA), 
GWGERACTE.MDFE_SERIE = (SELECT IMANIDF.SERIE FROM PSGACTE.DBO.IMANIDF 
							INNER JOIN PSGACTE.DBO.IMANINFE ON IMANIDF.COD_MANIFESTO = IMANINFE.COD_MANIFESTO
							WHERE IMANINFE.CHAVE_NF = @CHAVENOTA), 
GWGERACTE.MDFE_DATA = (SELECT IMANIDF.DATA_EMISSAO FROM PSGACTE.DBO.IMANIDF 
							INNER JOIN PSGACTE.DBO.IMANINFE ON IMANIDF.COD_MANIFESTO = IMANINFE.COD_MANIFESTO
							WHERE IMANINFE.CHAVE_NF = @CHAVENOTA)
WHERE GWGERACTE.CHAVE_NFE = @CHAVENOTA*/